#!/usr/bin/with-contenv bash

# install miniflux
if [ ! -d /config/www/miniflux ]; then
    mkdir -p /config/www
    echo "fetching miniflux files, this may take a little while"
    wget https://github.com/$(wget https://github.com/miniflux/miniflux/releases/latest -q -O - | egrep '/.*/.*/.*zip' -o) -q -O /tmp/miniflux.zip
    unzip /tmp/miniflux.zip -d /config/www/
    rm /tmp/miniflux.zip
fi

# permissions
chown -R abc:abc /config/www

# set cronjob
crontab /defaults/miniflux
